CREATE TABLE permission(
	id INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(250) NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE role(
	id INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(250) NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE User(
	id INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(250) NOT null,
	password VARCHAR(100) NOT null,
	phone VARCHAR(50) NOT null,
	cpf VARCHAR(50) NOT NULL,
	deleted BOOLEAN NOT null DEFAULT FALSE,
	idrole INTEGER NOT null,
	CONSTRAINT user_role_FK FOREIGN KEY (idrole) REFERENCES "role" (id)
);
